version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080" # Adjust the port if your Go API uses a different one
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # Pulls from .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  pgdata:
